---
driver:
  name: docker
  use_sudo: false
  privileged: true
  username: root
  cap_add:
    - sys_admin
sudo: false
provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -X stable 2016.11
  log_level: info
  is_file_root: true
  require_chef: false
  salt_copy_filter:
    - .bundle
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
  state_top:
    base:
      "*":
        - etcd
        - journald
platforms:
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd
suites:
  - name: etcd
    provisioner:
      pillars:
        top.sls:
          base:
            "*":
              - etcd
        etcd.sls:
          etcd:
            version: 3.2.5-1.el7
            cluster:
              client_port: 2379
              peer_port: 2380
              peers:
                kubemaster0:
                  ip: kubemaster0
                kubemaster1:
                  ip: kubemaster1
                kubemaster2:
                  ip: kubemaster2
